spring:
  application:
    name: know-way
  config:
    import:
      -  application-datasource.yml
      -  application-jwt.yml
      -  application-private.yml

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.config: DEBUG

application:
  domain: test