spring:
  application:
    name: know-way
  config:
    import:
      -  application-datasource.yml
      -  application-jwt.yml
      -  application-s3.yml
      -  application-redis.yml

logging:
  level:
#    org.springframework: DEBUG
#    org.springframework.data.redis: DEBUG
#    io.lettuce.core: DEBUG
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.config: DEBUG

application:
  domain: test

