cloud:
  aws:
    credentials:
      imageAccessKey: ${S3_IMAGE_ACCESS_KEY}
      imageSecretKey: ${S3_IMAGE_SECRET_KEY}
      recordAccessKey: ${S3_RECORD_ACCESS_KEY}
      recordSecretKey: ${S3_RECORD_SECRET_KEY}
    s3:
      imageBucket: ${S3_IMAGE_BUCKET_NAME}
      recordBucket: ${S3_RECORD_BUCKET_NAME}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
