spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}

    jdbc-url: jdbc:oracle:thin:(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g301b917317dd24_i7iavvhj984gmqtl_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ADMIN
    password: KosaKosa12345
    driver-class-name: oracle.jdbc.OracleDriver

